"""
Phase 1: Data quality report and assumptions log writer.

Writes markdown files to docs/ for reproducibility and handoff to downstream phases.
"""

from pathlib import Path
from typing import Dict, Any

import pandas as pd


def write_data_quality_report(
    quality_summary_df: pd.DataFrame,
    profile: Dict[str, Any],
    validation_report: Dict[str, Any],
    output_path: Path,
) -> None:
    """
    Write data quality report (markdown) with summary table and key metrics.
    """
    bad = validation_report.get("bad_data_drops") or {}
    lines = [
        "# Data Quality Report",
        "",
        "Generated by Phase 1: Data Quality & Profiling.",
        "",
        "## 1. Summary metrics",
        "",
        f"- **Total rows (raw):** {profile.get('row_count', 'N/A')}",
        f"- **Total columns:** {profile.get('column_count', 'N/A')}",
        f"- **Duplicate Ticket IDs:** {profile.get('duplicate_ticket_id_rows', 0)} rows "
        f"({profile.get('duplicate_ticket_id_count', 0)} unique IDs)",
        f"- **Rows dropped (bad data):** {bad.get('rows_dropped_total', 'N/A')} total",
        f"  - Closed with null First Response Time or Time to Resolution: {bad.get('rows_dropped_closed_missing_timestamps', 0)}",
        f"  - Time to Resolution < First Response Time (negative/invalid): {bad.get('rows_dropped_negative_or_invalid_time', 0)}",
        f"  - CSAT exists but ticket not Closed: {bad.get('rows_dropped_csat_not_closed', 0)}",
        "",
        "## 2. Logical consistency validation",
        "",
        f"- Closed tickets missing Resolution: {validation_report.get('closed_missing_resolution', 'N/A')}",
        f"- Open tickets with Time to Resolution set: {validation_report.get('open_with_resolution_time', 'N/A')}",
        f"- Validation passed: {validation_report.get('validation_passed', 'N/A')}",
        "",
        "## 3. Per-column summary",
        "",
    ]
    # Simple markdown table: header row then separator then data rows
    cols = list(quality_summary_df.columns)
    lines.append("| " + " | ".join(str(c) for c in cols) + " |")
    lines.append("| " + " | ".join("---" for _ in cols) + " |")
    for _, row in quality_summary_df.iterrows():
        lines.append("| " + " | ".join(str(row[c]) for c in cols) + " |")
    lines.extend(["", ""])

    with open(output_path, "w") as f:
        f.write("\n".join(lines))


def write_assumptions_log(
    output_path: Path,
    csat_missing_count: int,
    csat_missing_pct: float,
    bad_data_drops: dict,
) -> None:
    """
    Document cleaning decisions and assumptions for reproducibility.
    bad_data_drops: dict with rows_dropped_closed_missing_timestamps,
    rows_dropped_negative_or_invalid_time, rows_dropped_csat_not_closed, rows_dropped_total.
    """
    bad = bad_data_drops or {}
    total = bad.get("rows_dropped_total", 0)
    closed_ts = bad.get("rows_dropped_closed_missing_timestamps", 0)
    invalid_time = bad.get("rows_dropped_negative_or_invalid_time", 0)
    csat_not_closed = bad.get("rows_dropped_csat_not_closed", 0)
    lines = [
        "# Assumptions Log",
        "",
        "Phase 1 decisions and assumptions. Used by Business Case (Phase 4) and documentation.",
        "",
        "## Valid vs bad data (First Response Time / Time to Resolution)",
        "",
        "**Valid behavior (kept):** Open (First Response maybe null, Resolution null); "
        "In Progress / Pending Customer Response (First Response exists, Resolution null); "
        "Closed (both must exist). **Bad data (dropped):** (1) Closed but either timestamp null; "
        "(2) Both exist but Time to Resolution < First Response Time (negative duration); "
        "(3) CSAT present but ticket not Closed.",
        "",
        f"- **Total rows dropped (bad data):** {total}",
        f"  - Closed missing timestamps: {closed_ts}",
        f"  - Negative or invalid time order: {invalid_time}",
        f"  - CSAT exists but ticket not Closed: {csat_not_closed}",
        "",
        "## Data & SLA assumptions",
        "",
        "- **SLA thresholds (hours):** Critical = 4, High = 8, Medium = 24, Low = 48. "
        "Source: industry benchmarks; company-specific SLAs are not present in the dataset.",
        "- **Resolution duration:** Computed as (Time to Resolution - First Response Time) in hours. "
        "Only defined when both timestamps are present (typically Closed tickets).",
        "- **First response duration:** Not computable without ticket creation timestamp. "
        "Dataset does not include ticket open time; column `first_response_duration_hours` is null. "
        "`response_time_bucket` is therefore null.",
        "- **Ticket age (days):** (First Response Time - Date of Purchase). "
        "Approximates time from purchase to first agent response.",
        "",
        "## Customer Satisfaction Rating (CSAT)",
        "",
        f"- **Missing count:** {csat_missing_count}",
        f"- **Missing percentage:** {csat_missing_pct:.2f}%",
        "- **Decision:** Rows with missing CSAT are retained; exclude from CSAT-specific analysis "
        "(e.g. correlation with resolution time) or impute per analysis need. Not dropped at pipeline level.",
        "",
        "## Phase 4 cost baseline (placeholder)",
        "",
        "To be filled in Phase 4: agent salary, tickets per agent per day, cost per ticket, "
        "SLA breach cost, LTV, etc.",
        "",
    ]
    with open(output_path, "w") as f:
        f.write("\n".join(lines))
